with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/deriv-api-bff/pkg/core/handler:
    interfaces:
      Validator:
      RenderParser:
      WaitComposer:
  github.com/ksysoev/deriv-api-bff/pkg/core/validator:
    interfaces:
      schemaValidator:
  github.com/ksysoev/deriv-api-bff/pkg/core:
    interfaces:
      CallsRepo:
      Handler:
      ConnRegistry:
      APIProvider:
      Request:
  github.com/ksysoev/deriv-api-bff/pkg/api:
    interfaces:
      BFFService:
  github.com/ksysoev/deriv-api-bff/pkg/prov/router:
    interfaces:
      DerivAPI:
      HTTPAPI:
  github.com/ksysoev/deriv-api-bff/pkg/config:
    interfaces:
      BFFService:
      LocalSource:
      RemoteSource:
