with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/deriv-api-bff/pkg/core/handler:
    interfaces:
      Validator:
      RenderParser:
      WaitComposer:
      
