services:
  deriv-api-bff:
    image: ghcr.io/ksysoev/deriv-api-bff:main
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
        - BUILD=dev
    container_name: deriv-api-bff
    ports:
      - "8080:8080"
    environment:
      - SERVER_LISTEN=:8080
      - LOGLEVEL=debug
      - LOGTEXT=true
    volumes:
      - ./runtime/config.yaml:/runtime/config.yaml
    command: [
      "server", 
      "--config", 
      "/runtime/config.yaml", 
      ]
    depends_on:
      - nginx
      - etcd
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./samples/static:/var/www
      - ./samples/nginx.conf:/etc/nginx/conf.d/default.conf
  prometheus:
    image: prom/prometheus
    volumes:
      - "./samples/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    depends_on:
      - deriv-api-bff
  etcd:
    image: "quay.io/coreos/etcd:v3.4.34"
    command: [
      "etcd",
      "--name=etcd0",
      "--advertise-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001",
      "--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001",
      "--initial-advertise-peer-urls=http://0.0.0.0:2380",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--initial-cluster-token=etcd-cluster-1",
      "--initial-cluster=etcd0=http://0.0.0.0:2380",
      "--initial-cluster-state=new"
    ]
    ports:
    - "2379:2379"
    - 2380
    - 4001
