services:
  deriv-api-bff:
    image: ghcr.io/ksysoev/deriv-api-bff:main
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
        - BUILD=dev
    container_name: deriv-api-bff
    ports:
      - "8082:8082"
    environment:
      - SERVER_LISTEN=:8082
    command: ["server", "--config", "/runtime/config.yaml", "--log-level=debug", "--log-text"]
    
