services:
  deriv-api-bff:
    image: ghcr.io/ksysoev/deriv-api-bff:main
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
        - BUILD=dev
    container_name: deriv-api-bff
    ports:
      - "8080:8080"
    environment:
      - SERVER_LISTEN=:8080
      - LOGLEVEL=debug
      - LOGTEXT=true
    volumes:
      - ./runtime/config.yaml:/runtime/config.yaml
    command: [
      "server", 
      "--config", 
      "/runtime/config.yaml", 
      ]
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./samples/static:/var/www
      - ./samples/nginx.conf:/etc/nginx/conf.d/default.conf
