server:
  listen: ":8080"
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
etcd:
  servers: ["localhost:2379"]
  dialTimeoutSeconds: 5
api:
  calls:
    - method: "aggregate"
      params:
        country: 
          type: "string"
      backend:
        - response_body: "landing_company"
          allow: 
            - virtual_company
            - name
          fields_map:
            financial_company: "financial"
            gaming_company: "gaming"
          request_template: |
            {
              "landing_company": "{{ index .Params "country" }}",
              "req_id": {{ .ReqID }}
            }
        - response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: |
            {
              "website_status": 1,
              "req_id": {{ .ReqID }}
            }
    - method: "chain"
      backend:
        - response_body: "landing_company"
          depends_on: 
            - "website_status"
          allow: 
            - virtual_company
            - name
          fields_map:
            financial_company: "financial"
            gaming_company: "gaming"
          request_template: |
            {
              "landing_company": "{{ index .Resp "website_status" "clients_country" }}",
              "req_id": {{ .ReqID }}
            }
        - response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: |
            {
              "website_status": 1,
              "req_id": {{ .ReqID }}
            }
    - method: "config_country"
      params:
        country: 
          type: "string"
      backend:
        - method: "GET"
          url_template: 'http://nginx/country/{{ index .Params "country" }}.json'
          allow: 
            - region
            - subregion
            - name
            - alpha2Code
            - alpha3Code
            - callingCodes
            - capital
          fields_map:
            title: "title"
