server:
  listen: ":8080"
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
api:
  calls:
    - method: "aggregate"
      params:
        country: string
      backend:
        - response_body: "landing_company"
          allow: 
            - financial_company
            - gaming_company
          fields_map:
            financial_company: "financial"
            gaming_company: "gaming"
          request_template: |
            {
              "landing_company": "{{ index .Params "country" }}",
              "req_id": {{ .ReqID }}
            }
        - response_body: "website_status"
          allow: 
            - api_call_limits
            - clients_country
          request_template: |
            {
              "website_status": 1,
              "req_id": {{ .ReqID }}
            }
      