server:
  listen: ":8080"
  max_requests: 100
  max_requests_per_conn: 10
deriv:
  endpoint: "wss://ws.derivws.com/websockets/v3"
otel:
  prometheus:
    listen: ":8081"
    path: "/metrics"
api_source:
  etcd:
    servers: "localhost:2379"
    prefix: "api::"
  path: "./runtime/calls.yaml"
   
