// Code generated by mockery v2.46.3. DO NOT EDIT.

//go:build !compile

package validator

import mock "github.com/stretchr/testify/mock"

// MockschemaValidator is an autogenerated mock type for the schemaValidator type
type MockschemaValidator struct {
	mock.Mock
}

type MockschemaValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockschemaValidator) EXPECT() *MockschemaValidator_Expecter {
	return &MockschemaValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: data
func (_m *MockschemaValidator) Validate(data any) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockschemaValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockschemaValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - data any
func (_e *MockschemaValidator_Expecter) Validate(data interface{}) *MockschemaValidator_Validate_Call {
	return &MockschemaValidator_Validate_Call{Call: _e.mock.On("Validate", data)}
}

func (_c *MockschemaValidator_Validate_Call) Run(run func(data any)) *MockschemaValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockschemaValidator_Validate_Call) Return(_a0 error) *MockschemaValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockschemaValidator_Validate_Call) RunAndReturn(run func(any) error) *MockschemaValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockschemaValidator creates a new instance of MockschemaValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockschemaValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockschemaValidator {
	mock := &MockschemaValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
