// Code generated by mockery v2.46.3. DO NOT EDIT.

//go:build !compile

package core

import mock "github.com/stretchr/testify/mock"

// MockAPIProvider is an autogenerated mock type for the APIProvider type
type MockAPIProvider struct {
	mock.Mock
}

type MockAPIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIProvider) EXPECT() *MockAPIProvider_Expecter {
	return &MockAPIProvider_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *MockAPIProvider) Handle(_a0 *Conn, _a1 Request) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Conn, Request) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIProvider_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockAPIProvider_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 *Conn
//   - _a1 Request
func (_e *MockAPIProvider_Expecter) Handle(_a0 interface{}, _a1 interface{}) *MockAPIProvider_Handle_Call {
	return &MockAPIProvider_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *MockAPIProvider_Handle_Call) Run(run func(_a0 *Conn, _a1 Request)) *MockAPIProvider_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Conn), args[1].(Request))
	})
	return _c
}

func (_c *MockAPIProvider_Handle_Call) Return(_a0 error) *MockAPIProvider_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIProvider_Handle_Call) RunAndReturn(run func(*Conn, Request) error) *MockAPIProvider_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIProvider creates a new instance of MockAPIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIProvider {
	mock := &MockAPIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
