// Code generated by mockery v2.46.3. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, params, watcher, send
func (_m *MockHandler) Handle(ctx context.Context, params []byte, watcher Waiter, send Sender) (map[string]any, error) {
	ret := _m.Called(ctx, params, watcher, send)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 map[string]any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, Waiter, Sender) (map[string]any, error)); ok {
		return rf(ctx, params, watcher, send)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, Waiter, Sender) map[string]any); ok {
		r0 = rf(ctx, params, watcher, send)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, Waiter, Sender) error); ok {
		r1 = rf(ctx, params, watcher, send)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - params []byte
//   - watcher Waiter
//   - send Sender
func (_e *MockHandler_Expecter) Handle(ctx interface{}, params interface{}, watcher interface{}, send interface{}) *MockHandler_Handle_Call {
	return &MockHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, params, watcher, send)}
}

func (_c *MockHandler_Handle_Call) Run(run func(ctx context.Context, params []byte, watcher Waiter, send Sender)) *MockHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(Waiter), args[3].(Sender))
	})
	return _c
}

func (_c *MockHandler_Handle_Call) Return(_a0 map[string]any, _a1 error) *MockHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandler_Handle_Call) RunAndReturn(run func(context.Context, []byte, Waiter, Sender) (map[string]any, error)) *MockHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
