name: Build Docker image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=$(echo ${{ steps.meta.outputs.tags }} | cut -d ':' -f 2)" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
            BUILD=${{ github.sha }}
      - name: Scan docker image for vulnerabilities'
        id: docker_scan
        uses: crazy-max/ghaction-container-scan@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          image: ${{ steps.meta.outputs.tags }}
          severity_threshold: MEDIUM
          dockerfile: ./Dockerfile
      - name: Upload docker scan results
        if: ${{ steps.docker_scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.docker_scan.outputs.sarif }}
